trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: "0 0 * * 0"
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: "/miscellaneous/build_templates/variables.yml@templates"
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibraryPI
    value: product-readiness.omf-basic_api-dotnet.ocs.json
  - name: CredFileLibraryOP
    value: product-readiness.omf-basic_api-dotnet.pi.json
  - name: CredFileLibraryEDS
    value: product-readiness.omf-basic_api-dotnet.eds.json
  - name: analysisProject
    value: OMF_API_CPP

jobs:
  - job: Tests_OCS
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: "/miscellaneous/build_templates/config.yml@templates"
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryPI)
          filePath: /OMF_API

      - task: NuGetCommand@2
        displayName: 'Restore Packages'
        inputs:
          command: 'restore'

      - task: DotNetCoreCLI@2
        displayName: "Build Unit Test Application"
        inputs:
          command: 'build'

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: build

      - template: "/miscellaneous/build_templates/binskim.yml@templates"

      - template: "/miscellaneous/build_templates/analysis.yml@templates"
