trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: "0 0 * * 0"
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: "/miscellaneous/build_templates/variables.yml@templates"
  - name: CredFile
    value: appsettings.json
  - name: CertFile
    value: cert.cer
  - name: CredFileLibraryOCS
    value: product-readiness.omf-basic_api-cpp.ocs.json
  - name: RootCertificateOCS
    value: product-readiness.omf-basic_api-cpp.ocs.cer
  - name: CredFileLibraryPI
    value: product-readiness.omf-basic_api-cpp.pi.json
  - name: CredFileLibraryEDS
    value: product-readiness.omf-basic_api-cpp.eds.json
  - name: analysisProject
    value: OMF_API_CPP

jobs:
  - job: Tests_OCS
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: "/miscellaneous/build_templates/config.yml@templates"
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryOCS)
          filePath: /OMF_API

      - script: vcpkg install boost boost-json boost-date-time cppcodec openssl
        displayName: 'Install dependencies'

      - task: NuGetCommand@2
        displayName: 'Restore Packages'
        inputs:
          command: 'restore'
          feedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          
      - task: VSBuild@1
        inputs:
          configuration: $(BuildConfiguration)
          platform: $(BuildPlatform)
      
      - template: "/miscellaneous/build_templates/config.yml@templates"
        parameters:
          fileOriginal: $(CertFile)
          fileLibrary: $(RootCertificateOCS)
          filePath: '/Debug UnitTests'

      - task: PowerShell@1
        displayName: 'Load boost test adapter location'
        inputs:
          scriptType: inlineScript
          arguments: '-VisualStudioLocation:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"'
          inlineScript: |
            Param(
                [string]$VisualStudioLocation
            )
            
            $boostTestAdapter = Get-ChildItem -Recurse -Filter "boosttestadapter.dll" -Path $VisualStudioLocation
            $testAdapterDir = $boostTestAdapter.Directory.FullName
            if(-not(Test-Path $testAdapterDir))
            {
                Write-Error "Boost test adapter not found!"
            }
            Write-Host "Boost test adapter location: $testAdapterDir"
            Write-Host "##vso[task.setvariable variable=BoostTestAdapterLocation]$testAdapterDir"

      - task: VSTest@2
        inputs:
          testAssemblyVer2: '**\*.exe'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          vsTestVersion: 'Latest'
          pathtoCustomTestAdapters: '$(BoostTestAdapterLocation)'
          otherConsoleOptions: '/Platform:x86'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          failOnMinTestsNotRun: true
          diagnosticsEnabled: true
          rerunFailedTests: true
        condition: succeededOrFailed()

  - job: Tests_EDS
    dependsOn: Tests_OCS
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: "/miscellaneous/build_templates/config.yml@templates"
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryEDS)
          filePath: /OMF_API

      - task: NuGetCommand@2
        displayName: 'Restore Packages'
        inputs:
          command: 'restore'
          feedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          
      - task: VSBuild@1
        inputs:
          configuration: $(BuildConfiguration)
          platform: $(BuildPlatform)

      - task: VSTest@2
        inputs:
          testAssemblyVer2: '**\*.exe'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          vsTestVersion: 'Latest'
          pathtoCustomTestAdapters: '$(BoostTestAdapterLocation)'
          otherConsoleOptions: '/Platform:x86'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          failOnMinTestsNotRun: true
          diagnosticsEnabled: true
          rerunFailedTests: true
        condition: succeededOrFailed()

  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: build

      - template: "/miscellaneous/build_templates/binskim.yml@templates"

      - template: "/miscellaneous/build_templates/analysis.yml@templates"
