trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples
      
variables:
  - name: analysisProject
    value: OMF_API_CPP

jobs:
  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - template: '/miscellaneous/build_templates/appsettings.yml@templates'

        - task: NuGetCommand@2
          displayName: 'Restore Packages'
          inputs:
            command: 'restore'
            feedsToUse: 'config'
            nugetConfigPath: 'nuget.config'
